<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ResoDrive.Core\ResoDrive.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <RootNamespace>ResoDrive.Windows</RootNamespace>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
